import type { Municipio, Noticia, PQR } from "./types"

// ─── Global news (regional) ────────────────────────────────────────────────
export const noticiasRegionales: Noticia[] = [
  {
    id: "n-reg-1",
    titulo: "Primer Encuentro Regional CMJ Norte de Antioquia 2025",
    resumen:
      "Jóvenes de los 17 municipios se reúnen en Yarumal para construir la agenda juvenil regional del año.",
    contenido: `El pasado 15 de marzo, delegados de los Consejos Municipales de Juventud de los 17 municipios del Norte de Antioquia se congregaron en el municipio de Yarumal para el Primer Encuentro Regional 2025. El evento contó con más de 200 jóvenes que participaron en mesas de trabajo temáticas sobre educación, emprendimiento, cultura y participación ciudadana.\n\nDurante el encuentro se aprobó la Agenda Juvenil Regional 2025-2026, documento que guiará las acciones conjuntas de los CMJ durante los próximos dos años. Además, se eligió la Mesa Coordinadora Regional, encargada de articular los esfuerzos entre municipios.`,
    imagen: "/images/noticias/encuentro-regional.jpg",
    autor: "Secretaría Técnica CMJ Regional",
    fecha: "2025-03-16",
    categoria: "Eventos",
    destacada: true,
    tags: ["encuentro", "regional", "agenda juvenil"],
  },
  {
    id: "n-reg-2",
    titulo: "Convocatoria Fondo de Iniciativas Juveniles 2025",
    resumen:
      "Se abren 34 cupos para financiar proyectos liderados por jóvenes en los municipios del norte del departamento.",
    contenido: `La Gobernación de Antioquia, en alianza con los Consejos Municipales de Juventud del Norte, lanza la convocatoria para el Fondo de Iniciativas Juveniles 2025. Los proyectos podrán solicitar recursos entre $5.000.000 y $30.000.000 en categorías de cultura, emprendimiento, deporte y medio ambiente.\n\nLos interesados deben inscribirse a través del portal oficial antes del 30 de abril. Los proyectos deben ser liderados por jóvenes entre 14 y 28 años residentes en cualquiera de los 17 municipios del Norte de Antioquia.`,
    imagen: "/images/noticias/fondo-iniciativas.jpg",
    autor: "Gobernación de Antioquia",
    fecha: "2025-04-02",
    categoria: "Convocatorias",
    destacada: true,
    tags: ["fondo", "convocatoria", "proyectos"],
  },
  {
    id: "n-reg-3",
    titulo: "Capacitación en Liderazgo Juvenil: 120 jóvenes certificados",
    resumen:
      "El programa de formación política y liderazgo culminó con la certificación de representantes de todos los CMJ.",
    contenido: `Ciento veinte jóvenes líderes de los CMJ del Norte de Antioquia recibieron su certificado en el programa de formación en liderazgo político y participación ciudadana organizado por la Universidad de Antioquia, sede Yarumal, con el apoyo del Programa de las Naciones Unidas para el Desarrollo.\n\nEl programa abarcó módulos de democracia, derechos humanos, gestión de proyectos comunitarios y comunicación política. Los participantes realizaron prácticas en sus municipios durante 3 meses.`,
    imagen: "/images/noticias/capacitacion-liderazgo.jpg",
    autor: "UdeA Sede Yarumal",
    fecha: "2025-02-20",
    categoria: "Formacion",
    destacada: false,
    tags: ["formacion", "liderazgo", "certificacion"],
  },
  {
    id: "n-reg-4",
    titulo: "CMJ de Ituango inaugura centro comunitario juvenil",
    resumen:
      "Tras 18 meses de gestión, el Consejo Municipal de Juventud de Ituango logra la apertura del primer espacio dedicado exclusivamente a la juventud.",
    contenido: `El Consejo Municipal de Juventud de Ituango celebró la inauguración del Centro Comunitario Juvenil 'La Esperanza', un espacio de 400 m² destinado a actividades culturales, deportivas, formativas y de emprendimiento para jóvenes del municipio.\n\nEl proyecto fue financiado con recursos del Fondo de Iniciativas Juveniles 2024 y una contrapartida del municipio. El centro cuenta con sala de cómputo, zona de ensayos musicales, cancha cubierta y sala de reuniones.`,
    imagen: "/images/noticias/centro-ituango.jpg",
    autor: "CMJ Ituango",
    fecha: "2025-01-28",
    categoria: "Logros",
    destacada: false,
    tags: ["ituango", "infraestructura", "logro"],
  },
]

// ─── Municipalities ────────────────────────────────────────────────────────
export const municipios: Municipio[] = [
  {
    id: "m-01",
    slug: "angostura",
    nombre: "Angostura",
    descripcion:
      "Municipio conocido por la producción de caña de azúcar y panela. Su consejo juvenil trabaja en iniciativas de emprendimiento rural y cultura campesina.",
    poblacion: 13500,
    altitud: 1850,
    fundacion: 1830,
    imagen: "/images/municipios/angostura.jpg",
    escudo: "/images/escudos/angostura.png",
    alcalde: "José Ignacio Álvarez",
    region: "Norte de Antioquia",
    cmj: {
      periodo: "2024 – 2028",
      fechaPosesion: "15 de enero de 2024",
      normaLegal: "Acuerdo Municipal N.° 004 de 2024",
      numeroCurules: 9,
      mision:
        "Ser el órgano de representación, interlocución y participación de la juventud angosturana, promoviendo el desarrollo humano, la cultura y el emprendimiento rural.",
      vision:
        "En 2028, ser un consejo juvenil reconocido en el Norte de Antioquia por sus propuestas de política pública que transformen las condiciones de vida de los jóvenes rurales.",
      objetivos: [
          "Promover la participación activa de los jóvenes en los asuntos públicos del municipio.",
          "Gestionar proyectos de emprendimiento rural y agroindustria juvenil.",
          "Fortalecer la identidad cultural y el sentido de pertenencia territorial.",
          "Articularse con la administración municipal para la formulación de política pública de juventud.",
      ],
        redes: {
          facebook: "CMJ Angostura Oficial",
          instagram: "@cmj_angostura",
        },
    },
    integrantes: [
      {
        id: "i-ang-1",
        municipioId: "m-01",
        nombre: "Laura Camila Restrepo",
        cargo: "Presidente",
        foto: "/images/integrantes/laura-restrepo.jpg",
        email: "lcrestrepo.cmj@angostura.gov.co",
        telefono: "3142567890",
        edad: 22,
        periodoInicio: "2024-01-15",
        periodoFin: "2026-01-15",
        bio: "Estudiante de Administración de Empresas. Apasionada por el desarrollo rural y el emprendimiento juvenil.",
      },
      {
        id: "i-ang-2",
        municipioId: "m-01",
        nombre: "Carlos Andrés Ospina",
        cargo: "Vicepresidente",
        foto: "/images/integrantes/carlos-ospina.jpg",
        email: "caospina.cmj@angostura.gov.co",
        telefono: "3118890123",
        edad: 20,
        periodoInicio: "2024-01-15",
        periodoFin: "2026-01-15",
        bio: "Técnico en Gestión Ambiental. Promotor de huertos comunitarios y proyectos ecológicos.",
      },
      {
        id: "i-ang-3",
        municipioId: "m-01",
        nombre: "Valentina García",
        cargo: "Secretario/a",
        foto: "/images/integrantes/valentina-garcia.jpg",
        email: "vgarcia.cmj@angostura.gov.co",
        telefono: "3206541234",
        edad: 19,
        periodoInicio: "2024-01-15",
        periodoFin: "2026-01-15",
        bio: "Bachiller con interés en comunicación comunitaria y periodismo juvenil.",
      },
    ],
    proyectos: [
      {
        id: "p-ang-1",
        municipioId: "m-01",
        titulo: "Escuela de Emprendimiento Rural Joven",
        descripcion:
          "Formación en habilidades empresariales para jóvenes del área rural con enfoque en agroindustria.",
        estado: "En curso",
        fechaInicio: "2025-02-01",
        presupuesto: 18000000,
        beneficiarios: 45,
        categoria: "Emprendimiento",
        imagen: "/images/proyectos/emprendimiento-rural.jpg",
      },
      {
        id: "p-ang-2",
        municipioId: "m-01",
        titulo: "Festival de la Panela Joven",
        descripcion:
          "Evento anual que celebra la identidad panelera del municipio con jóvenes como protagonistas.",
        estado: "Planificado",
        fechaInicio: "2025-08-15",
        presupuesto: 8000000,
        beneficiarios: 200,
        categoria: "Cultura",
        imagen: "/images/proyectos/festival-panela.jpg",
      },
    ],
    noticias: [
      {
        id: "n-ang-1",
        municipioId: "m-01",
        titulo: "CMJ Angostura inicia programa de becas universitarias",
        resumen:
          "Convenio con el SENA y la UdeA beneficiará a 10 jóvenes del municipio con educación superior gratuita.",
        contenido:
          "El CMJ de Angostura firmó un convenio estratégico con el SENA Regional Antioquia y la Universidad de Antioquia para otorgar 10 becas de educación superior a jóvenes en condición de vulnerabilidad. Las becas cubren matrícula, materiales y transporte para los beneficiarios.",
        imagen: "/images/noticias/becas-angostura.jpg",
        autor: "CMJ Angostura",
        fecha: "2025-03-10",
        categoria: "Educacion",
        destacada: true,
        tags: ["becas", "educacion", "SENA"],
      },
    ],
  },
  {
    id: "m-02",
    slug: "belmira",
    nombre: "Belmira",
    descripcion:
      "Municipio lechero y páramo, reconocido por sus ecosistemas naturales. El CMJ impulsa la educación ambiental y el turismo sostenible.",
    poblacion: 6200,
    altitud: 2550,
    fundacion: 1814,
    imagen: "/images/municipios/belmira.jpg",
    escudo: "/images/escudos/belmira.png",
    alcalde: "Diana Patricia Monsalve",
    region: "Norte de Antioquia",
    cmj: {
      periodo: "2024 – 2028",
      fechaPosesion: "1 de febrero de 2024",
      normaLegal: "Acuerdo Municipal N.° 002 de 2024",
      numeroCurules: 7,
      mision:
        "Representar a la juventud de Belmira y sus veredas, impulsando la conservación ambiental y el turismo sostenible como motores del desarrollo juvenil.",
      vision:
        "Ser referente departamental en gestión ambiental juvenil y ecoturismo comunitario para el año 2028.",
      objetivos: [
          "Liderar iniciativas de conservación del páramo y los recursos hídricos.",
          "Fomentar el ecoturismo comunitario como fuente de empleo para los jóvenes.",
          "Garantizar espacios de participación para jóvenes rurales y de casco urbano.",
          "Establecer alianzas con universidades y ONG ambientales.",
      ],
        redes: {
          instagram: "@cmjbelmira",
        },
    },
    integrantes: [
      {
        id: "i-bel-1",
        municipioId: "m-02",
        nombre: "Andrés Felipe Zapata",
        cargo: "Presidente",
        foto: "/images/integrantes/andres-zapata.jpg",
        email: "afzapata.cmj@belmira.gov.co",
        telefono: "3157892345",
        edad: 24,
        periodoInicio: "2024-02-01",
        periodoFin: "2026-02-01",
        bio: "Biólogo egresado de la UdeA. Lidera proyectos de conservación del páramo de Belmira.",
      },
      {
        id: "i-bel-2",
        municipioId: "m-02",
        nombre: "Sara Milena Cano",
        cargo: "Vicepresidente",
        foto: "/images/integrantes/sara-cano.jpg",
        email: "smcano.cmj@belmira.gov.co",
        telefono: "3012345678",
        edad: 21,
        periodoInicio: "2024-02-01",
        periodoFin: "2026-02-01",
        bio: "Técnica en Turismo Sostenible. Promotora de rutas ecoturísticas en el municipio.",
      },
    ],
    proyectos: [
      {
        id: "p-bel-1",
        municipioId: "m-02",
        titulo: "Guardianes del Páramo",
        descripcion:
          "Programa de educación ambiental y monitoreo comunitario del páramo de Belmira con jóvenes líderes.",
        estado: "En curso",
        fechaInicio: "2024-09-01",
        presupuesto: 22000000,
        beneficiarios: 60,
        categoria: "Medio Ambiente",
        imagen: "/images/proyectos/guardianes-paramo.jpg",
      },
    ],
    noticias: [
      {
        id: "n-bel-1",
        municipioId: "m-02",
        titulo: "Belmira lanza ruta ecoturística juvenil",
        resumen: "El CMJ presenta el primer circuito turístico guiado por jóvenes del páramo.",
        contenido:
          "El Consejo Municipal de Juventud de Belmira presentó oficialmente la Ruta Ecoturística Juvenil, un recorrido de 2 días por los atractivos naturales del municipio guiado exclusivamente por jóvenes locales capacitados en interpretación ambiental y primeros auxilios.",
        imagen: "/images/noticias/ecoturismo-belmira.jpg",
        autor: "CMJ Belmira",
        fecha: "2025-02-14",
        categoria: "Turismo",
        destacada: false,
        tags: ["turismo", "paramo", "naturaleza"],
      },
    ],
  },
  {
    id: "m-03",
    slug: "briceno",
    nombre: "Briceño",
    descripcion:
      "Municipio en proceso de reconstrucción del tejido social. El CMJ trabaja fuertemente en reconciliación, paz y oportunidades para la juventud.",
    poblacion: 9800,
    altitud: 1200,
    fundacion: 1880,
    imagen: "/images/municipios/briceno.jpg",
    escudo: "/images/escudos/briceno.png",
    alcalde: "Miguel Ángel Montoya",
    region: "Norte de Antioquia",
    cmj: {
      periodo: "2024 – 2028",
      fechaPosesion: "20 de enero de 2024",
      normaLegal: "Acuerdo Municipal N.° 001 de 2024",
      numeroCurules: 9,
      mision:
        "Contribuir a la reconciliación y construcción de paz en Briceño, abriendo oportunidades para que los jóvenes sean protagonistas del posconflicto y la reintegración social.",
      vision:
        "En 2028, ser un consejo que haya transformado la narrativa del municipio, posicionando a sus jóvenes como constructores de paz reconocidos a nivel nacional.",
      objetivos: [
          "Promover la convivencia pacífica y la reconciliación entre los jóvenes del municipio.",
          "Gestionar oportunidades de formación y empleo para jóvenes en contexto de posconflicto.",
          "Visibilizar las historias y proyectos de vida de la juventud de Briceño.",
          "Articular acciones con la Unidad para las Víctimas y la Agencia para la Reincorporación.",
      ],
        redes: {
          facebook: "CMJ Briceño Paz",
          instagram: "@cmj_briceno",
        },
    },
    integrantes: [
      {
        id: "i-bri-1",
        municipioId: "m-03",
        nombre: "Yesenia Paola Lopera",
        cargo: "Presidente",
        foto: "/images/integrantes/yesenia-lopera.jpg",
        email: "yplopera.cmj@briceno.gov.co",
        telefono: "3168901234",
        edad: 23,
        periodoInicio: "2024-01-20",
        periodoFin: "2026-01-20",
        bio: "Comunicadora social con enfoque en paz y reconciliación. Líder comunitaria reconocida.",
      },
      {
        id: "i-bri-2",
        municipioId: "m-03",
        nombre: "Jhon Esteban Arango",
        cargo: "Secretario/a",
        foto: "/images/integrantes/jhon-arango.jpg",
        email: "jearango.cmj@briceno.gov.co",
        telefono: "3129012345",
        edad: 20,
        periodoInicio: "2024-01-20",
        periodoFin: "2026-01-20",
        bio: "Estudiante de Derecho. Promotor de los derechos de la juventud en territorios afectados por el conflicto.",
      },
    ],
    proyectos: [
      {
        id: "p-bri-1",
        municipioId: "m-03",
        titulo: "Tejiendo Paz desde la Juventud",
        descripcion:
          "Talleres de arte, memoria histórica y reconciliación para jóvenes víctimas y gestores de paz.",
        estado: "En curso",
        fechaInicio: "2024-06-01",
        presupuesto: 35000000,
        beneficiarios: 120,
        categoria: "Cultura",
        imagen: "/images/proyectos/tejiendo-paz.jpg",
      },
    ],
    noticias: [
      {
        id: "n-bri-1",
        municipioId: "m-03",
        titulo: "CMJ Briceño gana premio nacional de paz",
        resumen: "El proyecto 'Tejiendo Paz' es reconocido a nivel nacional por su impacto en reconciliación.",
        contenido:
          "El proyecto 'Tejiendo Paz desde la Juventud' del CMJ de Briceño fue galardonado en los Premios Nacionales de Paz 2025 en la categoría Participación Juvenil. El premio reconoce el trabajo de los jóvenes en la reconstrucción del tejido social del municipio.",
        imagen: "/images/noticias/premio-paz-briceno.jpg",
        autor: "CMJ Briceño",
        fecha: "2025-04-01",
        categoria: "Logros",
        destacada: true,
        tags: ["paz", "premio", "reconciliacion"],
      },
    ],
  },
  {
    id: "m-04",
    slug: "campamento",
    nombre: "Campamento",
    descripcion:
      "Municipio cafetero y minero con jóvenes comprometidos en el desarrollo económico local y la transición hacia economías más sostenibles.",
    poblacion: 8500,
    altitud: 1750,
    fundacion: 1878,
    imagen: "/images/municipios/campamento.jpg",
    escudo: "/images/escudos/campamento.png",
    alcalde: "Luz Marina Velásquez",
    region: "Norte de Antioquia",
    cmj: {
      periodo: "2024 – 2028",
      fechaPosesion: "10 de febrero de 2024",
      normaLegal: "Acuerdo Municipal N.° 003 de 2024",
      numeroCurules: 7,
      mision:
        "Representar a los jóvenes del municipio de Campamento, promoviendo el desarrollo cultural, deportivo y productivo en el territorio.",
      vision:
        "Consolidar un consejo activo y propositivo que logre mejorar la calidad de vida de los jóvenes campamentanos mediante la gestión de proyectos de impacto social.",
      objetivos: [
          "Fortalecer los espacios deportivos y culturales para la juventud.",
          "Gestionar proyectos de formación técnica y emprendimiento.",
          "Garantizar la participación juvenil en los planes de desarrollo municipal.",
          "Promover la salud mental y el bienestar integral de los jóvenes.",
      ],
        redes: {
          instagram: "@cmjcampamento",
        },
    },
    integrantes: [
      {
        id: "i-cam-1",
        municipioId: "m-04",
        nombre: "Sebastián Vargas",
        cargo: "Presidente",
        foto: "/images/integrantes/sebastian-vargas.jpg",
        email: "svargas.cmj@campamento.gov.co",
        telefono: "3190123456",
        edad: 25,
        periodoInicio: "2024-03-01",
        periodoFin: "2026-03-01",
        bio: "Ingeniero ambiental en formación. Trabaja en propuestas de minería responsable con comunidades.",
      },
    ],
    proyectos: [
      {
        id: "p-cam-1",
        municipioId: "m-04",
        titulo: "Café Joven: Marca Comunitaria",
        descripcion:
          "Creación de una marca de café especial gestionada por jóvenes cafeteros del municipio.",
        estado: "En curso",
        fechaInicio: "2025-01-15",
        presupuesto: 25000000,
        beneficiarios: 35,
        categoria: "Emprendimiento",
        imagen: "/images/proyectos/cafe-joven.jpg",
      },
    ],
    noticias: [
      {
        id: "n-cam-1",
        municipioId: "m-04",
        titulo: "Café Joven de Campamento debuta en la Feria de Medellín",
        resumen: "La marca de café especial creada por jóvenes campamenteros llega a la capital antioqueña.",
        contenido:
          "El café especial producido y comercializado por jóvenes del CMJ de Campamento hizo su debut en la Feria de las Flores de Medellín, generando pedidos por más de $15 millones. El proyecto demuestra el potencial del emprendimiento juvenil rural.",
        imagen: "/images/noticias/cafe-feria-medellin.jpg",
        autor: "CMJ Campamento",
        fecha: "2025-03-25",
        categoria: "Emprendimiento",
        destacada: false,
        tags: ["cafe", "emprendimiento", "feria"],
      },
    ],
  },
  {
    id: "m-05",
    slug: "carolina-del-principe",
    nombre: "Carolina del Príncipe",
    descripcion:
      "Uno de los municipios más antiguos de Antioquia, con un rico patrimonio histórico y arquitectónico. El CMJ promueve el turismo cultural.",
    poblacion: 5800,
    altitud: 1780,
    fundacion: 1788,
    imagen: "/images/municipios/carolina.jpg",
    escudo: "/images/escudos/carolina.png",
    alcalde: "Roberto Emilio Soto",
    region: "Norte de Antioquia",
    cmj: {
      periodo: "2024 – 2028",
      fechaPosesion: "5 de febrero de 2024",
      normaLegal: "Acuerdo Municipal N.° 002 de 2024",
      numeroCurules: 7,
      mision:
        "Preservar y difundir el patrimonio histórico y cultural de Carolina del Príncipe mediante la acción juvenil organizada y propositiva.",
      vision:
        "Ser un consejo referente en gestión cultural y turística, reconocido por poner a los jóvenes carolineros como guardianes del patrimonio municipal.",
      objetivos: [
          "Proteger y promover el patrimonio arquitectónico e histórico del municipio.",
          "Impulsar el turismo cultural con los jóvenes como guías y gestores.",
          "Fortalecer las expresiones artísticas locales como la música y la danza.",
          "Crear alianzas con el Ministerio de Cultura y el Instituto de Patrimonio.",
      ],
        redes: {
          facebook: "CMJ Carolina del Príncipe",
          instagram: "@cmj_carolinadprincipe",
        },
    },
    integrantes: [
      {
        id: "i-car-1",
        municipioId: "m-05",
        nombre: "María Alejandra Henao",
        cargo: "Presidente",
        foto: "/images/integrantes/maria-henao.jpg",
        email: "mahenao.cmj@carolina.gov.co",
        telefono: "3101234567",
        edad: 22,
        periodoInicio: "2024-01-10",
        periodoFin: "2026-01-10",
        bio: "Historiadora y gestora cultural. Apasionada por el patrimonio de Carolina del Príncipe.",
      },
      {
        id: "i-car-2",
        municipioId: "m-05",
        nombre: "Felipe Andrés Ríos",
        cargo: "Vocal",
        foto: "/images/integrantes/felipe-rios.jpg",
        email: "farios.cmj@carolina.gov.co",
        telefono: "3123456789",
        edad: 19,
        periodoInicio: "2024-01-10",
        periodoFin: "2026-01-10",
        bio: "Artesano y diseñador gráfico. Promueve las artes tradicionales entre los jóvenes.",
      },
    ],
    proyectos: [
      {
        id: "p-car-1",
        municipioId: "m-05",
        titulo: "Rutas de Memoria: Turismo Patrimonial Joven",
        descripcion:
          "Circuitos turísticos por el centro histórico de Carolina liderados y narrados por jóvenes del municipio.",
        estado: "Completado",
        fechaInicio: "2024-04-01",
        fechaFin: "2024-12-15",
        presupuesto: 12000000,
        beneficiarios: 500,
        categoria: "Cultura",
        imagen: "/images/proyectos/rutas-memoria.jpg",
      },
    ],
    noticias: [
      {
        id: "n-car-1",
        municipioId: "m-05",
        titulo: "Carolina del Príncipe declara el Año del Patrimonio Juvenil",
        resumen: "El municipio y el CMJ firman acuerdo para proteger y difundir el patrimonio cultural entre la juventud.",
        contenido:
          "El concejo municipal aprobó la declaratoria del Año del Patrimonio Juvenil 2025, impulsada por el CMJ de Carolina del Príncipe. Se realizarán exposiciones, talleres de restauración y visitas guiadas durante todo el año.",
        imagen: "/images/noticias/patrimonio-carolina.jpg",
        autor: "CMJ Carolina del Príncipe",
        fecha: "2025-01-20",
        categoria: "Cultura",
        destacada: false,
        tags: ["patrimonio", "cultura", "acuerdo"],
      },
    ],
  },
  {
    id: "m-06",
    slug: "don-matias",
    nombre: "Don Matías",
    descripcion:
      "Municipio textilero del norte antioqueño. El CMJ apoya el emprendimiento en diseño de modas y la industria textil juvenil.",
    poblacion: 19000,
    altitud: 2350,
    fundacion: 1857,
    imagen: "/images/municipios/don-matias.jpg",
    escudo: "/images/escudos/don-matias.png",
    alcalde: "Ana Sofía Bermúdez",
    region: "Norte de Antioquia",
    cmj: {
      periodo: "2024 – 2028",
      fechaPosesion: "20 de febrero de 2024",
      normaLegal: "Acuerdo Municipal N.° 005 de 2024",
      numeroCurules: 11,
      mision:
        "Articular a los jóvenes de Don Matías con el sector productivo e industrial del municipio, generando oportunidades de empleo, formación y emprendimiento.",
      vision:
        "Para 2028, ser un consejo que haya vinculado a más de 500 jóvenes al sector productivo formal del municipio, con programas de formación y pasantías empresariales.",
      objetivos: [
          "Generar alianzas con empresas textiles y del sector industrial para pasantías juveniles.",
          "Promover el emprendimiento tecnológico y la innovación entre los jóvenes.",
          "Garantizar el acceso a educación técnica y superior para los jóvenes del municipio.",
          "Fortalecer la política pública de juventud articulada con el Plan de Desarrollo.",
      ],
        redes: {
          instagram: "@cmjdonmatias",
          tiktok: "@cmjdonmatias",
        },
    },
    integrantes: [
      {
        id: "i-don-1",
        municipioId: "m-06",
        nombre: "Juliana Marín",
        cargo: "Presidente",
        foto: "/images/integrantes/juliana-marin.jpg",
        email: "jmarin.cmj@donmatias.gov.co",
        telefono: "3134567890",
        edad: 26,
        periodoInicio: "2024-02-15",
        periodoFin: "2026-02-15",
        bio: "Diseñadora de modas. Dirige proyectos de moda sostenible con jóvenes del sector textil.",
      },
      {
        id: "i-don-2",
        municipioId: "m-06",
        nombre: "David Camilo Pérez",
        cargo: "Tesorero/a",
        foto: "/images/integrantes/david-perez.jpg",
        email: "dcperez.cmj@donmatias.gov.co",
        telefono: "3145678901",
        edad: 23,
        periodoInicio: "2024-02-15",
        periodoFin: "2026-02-15",
        bio: "Contador público en formación. Maneja las finanzas del consejo con transparencia.",
      },
    ],
    proyectos: [
      {
        id: "p-don-1",
        municipioId: "m-06",
        titulo: "Moda Norte: Colección Joven",
        descripcion:
          "Pasarela anual de moda sostenible con colecciones diseñadas y confeccionadas por jóvenes del municipio.",
        estado: "Planificado",
        fechaInicio: "2025-09-01",
        presupuesto: 15000000,
        beneficiarios: 80,
        categoria: "Emprendimiento",
        imagen: "/images/proyectos/moda-norte.jpg",
      },
    ],
    noticias: [
      {
        id: "n-don-1",
        municipioId: "m-06",
        titulo: "Jóvenes de Don Matías exportan moda a Europa",
        resumen: "Un colectivo juvenil textil logra su primer contrato de exportación hacia Alemania.",
        contenido:
          "El colectivo 'Hilo Norte', apoyado por el CMJ de Don Matías, firmó un contrato con una empresa distribuidora alemana para exportar colecciones de ropa artesanal. Este logro es fruto de 2 años de trabajo y formación en diseño y comercio exterior.",
        imagen: "/images/noticias/exportacion-don-matias.jpg",
        autor: "CMJ Don Matías",
        fecha: "2025-04-08",
        categoria: "Emprendimiento",
        destacada: true,
        tags: ["exportacion", "textil", "logro"],
      },
    ],
  },
  {
    id: "m-07",
    slug: "entrerrios",
    nombre: "Entrerríos",
    descripcion:
      "Municipio ganadero y lechero con tradición agropecuaria. El CMJ trabaja en tecnología agrícola y desarrollo rural juvenil.",
    poblacion: 7200,
    altitud: 2500,
    fundacion: 1847,
    imagen: "/images/municipios/entrerrios.jpg",
    escudo: "/images/escudos/entrerrios.png",
    alcalde: "Hernán Darío Calle",
    region: "Norte de Antioquia",
    cmj: {
      periodo: "2024 – 2028",
      fechaPosesion: "8 de marzo de 2024",
      normaLegal: "Acuerdo Municipal N.° 002 de 2024",
      numeroCurules: 7,
      mision:
        "Fomentar el bienestar, la participación y el desarrollo integral de los jóvenes de Entrerríos, con énfasis en el cuidado ambiental y la producción agropecuaria sostenible.",
      vision:
        "Consolidarnos como un consejo que conecte a los jóvenes con el potencial agropecuario y natural de Entrerríos, generando empleo verde y sostenible.",
      objetivos: [
          "Promover la agricultura sostenible y la ganadería responsable entre los jóvenes.",
          "Fortalecer el vínculo de los jóvenes con el campo y las tradiciones rurales.",
          "Gestionar proyectos de conectividad y acceso a tecnología en zonas rurales.",
          "Articularse con el SENA para formación técnica agropecuaria.",
      ],
        redes: {
          instagram: "@cmj_entrerrios",
        },
    },
    integrantes: [
      {
        id: "i-ent-1",
        municipioId: "m-07",
        nombre: "Isabella Correa",
        cargo: "Presidente",
        foto: "/images/integrantes/isabella-correa.jpg",
        email: "icorrea.cmj@entrerrios.gov.co",
        telefono: "3156789012",
        edad: 21,
        periodoInicio: "2024-01-25",
        periodoFin: "2026-01-25",
        bio: "Zootecnista en formación. Promueve la tecnificación del campo entre jóvenes ganaderos.",
      },
    ],
    proyectos: [
      {
        id: "p-ent-1",
        municipioId: "m-07",
        titulo: "AgriTech Joven Norte",
        descripcion:
          "Capacitación en tecnologías agrícolas para jóvenes rurales: drones, sensores y agricultura de precisión.",
        estado: "En curso",
        fechaInicio: "2025-03-01",
        presupuesto: 28000000,
        beneficiarios: 40,
        categoria: "Educacion",
        imagen: "/images/proyectos/agritech.jpg",
      },
    ],
    noticias: [
      {
        id: "n-ent-1",
        municipioId: "m-07",
        titulo: "Entrerríos pionero en uso de drones agrícolas por jóvenes",
        resumen: "El CMJ lanzó el primer programa de capacitación en drones agrícolas para jóvenes campesinos.",
        contenido:
          "El CMJ de Entrerríos, en convenio con el SENA, inició la primera cohorte de capacitación en pilotaje de drones agrícolas para jóvenes mayores de 18 años. El programa forma en aplicación de agroquímicos de precisión, mapeo de cultivos y análisis de datos.",
        imagen: "/images/noticias/drones-entrerrios.jpg",
        autor: "CMJ Entrerríos",
        fecha: "2025-03-15",
        categoria: "Tecnologia",
        destacada: false,
        tags: ["drones", "agricultura", "SENA"],
      },
    ],
  },
  {
    id: "m-08",
    slug: "gomez-plata",
    nombre: "Gómez Plata",
    descripcion:
      "Municipio con vocación minera e histórica. El CMJ impulsa proyectos de deporte y cultura para alejar a los jóvenes de dinámicas negativas.",
    poblacion: 11200,
    altitud: 1300,
    fundacion: 1875,
    imagen: "/images/municipios/gomez-plata.jpg",
    escudo: "/images/escudos/gomez-plata.png",
    alcalde: "Carlos Eduardo Muñoz",
    region: "Norte de Antioquia",
    cmj: {
      periodo: "2024 – 2028",
      fechaPosesion: "12 de febrero de 2024",
      normaLegal: "Acuerdo Municipal N.° 003 de 2024",
      numeroCurules: 7,
      mision:
        "Impulsar el desarrollo cultural, artístico y económico de la juventud de Gómez Plata, aprovechando la riqueza patrimonial y minera del municipio de forma responsable.",
      vision:
        "Ser un consejo que haya transformado las oportunidades de los jóvenes gómezplateños, con proyectos innovadores en cultura, tecnología y medio ambiente.",
      objetivos: [
          "Promover expresiones culturales y artísticas autóctonas.",
          "Gestionar proyectos de formación tecnológica y digital.",
          "Impulsar el turismo de aventura y la oferta de ocio saludable para jóvenes.",
          "Fortalecer la participación política juvenil en espacios de decisión municipal.",
      ],
        redes: {
          instagram: "@cmjgomezplata",
        },
    },
    integrantes: [
      {
        id: "i-gom-1",
        municipioId: "m-08",
        nombre: "Nicolás Betancur",
        cargo: "Presidente",
        foto: "/images/integrantes/nicolas-betancur.jpg",
        email: "nbetancur.cmj@gomezplata.gov.co",
        telefono: "3167890123",
        edad: 24,
        periodoInicio: "2024-02-10",
        periodoFin: "2026-02-10",
        bio: "Educador físico. Lidera liga deportiva juvenil y escuelas de fútbol comunitarias.",
      },
    ],
    proyectos: [
      {
        id: "p-gom-1",
        municipioId: "m-08",
        titulo: "Liga Deportiva Juvenil Norte",
        descripcion:
          "Torneos intermunicipales de fútbol, baloncesto y atletismo para jóvenes del norte antioqueño.",
        estado: "En curso",
        fechaInicio: "2025-01-20",
        presupuesto: 20000000,
        beneficiarios: 250,
        categoria: "Deporte",
        imagen: "/images/proyectos/liga-deportiva.jpg",
      },
    ],
    noticias: [
      {
        id: "n-gom-1",
        municipioId: "m-08",
        titulo: "Gómez Plata acoge el torneo intermunicipal de fútbol",
        resumen: "La Liga Juvenil Norte reunió a equipos de 8 municipios en emocionantes jornadas deportivas.",
        contenido:
          "El municipio de Gómez Plata fue sede de la fase regional de la Liga Deportiva Juvenil Norte. Participaron 16 equipos de 8 municipios, con más de 300 jóvenes compitiendo en disciplinas de fútbol sala, microfútbol y atletismo.",
        imagen: "/images/noticias/torneo-gomez-plata.jpg",
        autor: "CMJ Gómez Plata",
        fecha: "2025-02-28",
        categoria: "Deporte",
        destacada: false,
        tags: ["deporte", "torneo", "liga"],
      },
    ],
  },
  {
    id: "m-09",
    slug: "guadalupe",
    nombre: "Guadalupe",
    descripcion:
      "Municipio cafetero y cacaotero con bellezas naturales. El CMJ trabaja en agroturismo y emprendimiento juvenil cafetero.",
    poblacion: 7500,
    altitud: 1650,
    fundacion: 1910,
    imagen: "/images/municipios/guadalupe.jpg",
    escudo: "/images/escudos/guadalupe.png",
    alcalde: "Olga Lucia Palacio",
    region: "Norte de Antioquia",
    cmj: {
      periodo: "2024 – 2028",
      fechaPosesion: "18 de enero de 2024",
      normaLegal: "Acuerdo Municipal N.° 001 de 2024",
      numeroCurules: 7,
      mision:
        "Representar a los jóvenes de Guadalupe y promover su participación activa en la vida política, cultural y ambiental del municipio, desde una perspectiva de derechos.",
      vision:
        "Construir, junto con la administración municipal, una política pública de juventud que garantice los derechos de todos los jóvenes guadalupanos al 2028.",
      objetivos: [
          "Fortalecer la participación juvenil en los organismos de decisión municipal.",
          "Promover el cuidado ambiental y la gestión del riesgo con jóvenes.",
          "Articular acciones con el sector salud para garantizar el bienestar juvenil.",
          "Desarrollar proyectos culturales que rescaten las tradiciones locales.",
      ],
        redes: {
          instagram: "@cmjguadalupe_ant",
        },
    },
    integrantes: [
      {
        id: "i-gua-1",
        municipioId: "m-09",
        nombre: "Andrea Sofía Llano",
        cargo: "Presidente",
        foto: "/images/integrantes/andrea-llano.jpg",
        email: "asllano.cmj@guadalupe.gov.co",
        telefono: "3178901234",
        edad: 22,
        periodoInicio: "2024-03-05",
        periodoFin: "2026-03-05",
        bio: "Agrónoma. Especialista en producción de cacao orgánico y mercados campesinos.",
      },
    ],
    proyectos: [
      {
        id: "p-gua-1",
        municipioId: "m-09",
        titulo: "Cacao Joven de Guadalupe",
        descripcion:
          "Producción y comercialización de chocolate artesanal de origen por jóvenes cacaoteros.",
        estado: "En curso",
        fechaInicio: "2024-11-01",
        presupuesto: 16000000,
        beneficiarios: 30,
        categoria: "Emprendimiento",
        imagen: "/images/proyectos/cacao-joven.jpg",
      },
    ],
    noticias: [
      {
        id: "n-gua-1",
        municipioId: "m-09",
        titulo: "Chocolate de Guadalupe llega a tiendas gourmet de Medellín",
        resumen: "El proyecto Cacao Joven logra presencia en 5 tiendas especializadas de la ciudad.",
        contenido:
          "El chocolate artesanal de origen producido por jóvenes de Guadalupe, bajo el proyecto Cacao Joven del CMJ, llegó a los estantes de 5 tiendas gourmet de Medellín. El producto destaca por su proceso de fermentación natural y empaque artesanal.",
        imagen: "/images/noticias/chocolate-guadalupe.jpg",
        autor: "CMJ Guadalupe",
        fecha: "2025-03-05",
        categoria: "Emprendimiento",
        destacada: false,
        tags: ["cacao", "chocolate", "comercializacion"],
      },
    ],
  },
  {
    id: "m-10",
    slug: "ituango",
    nombre: "Ituango",
    descripcion:
      "Municipio en transformación con la llegada del proyecto hidroeléctrico Ituango. El CMJ trabaja en derechos juveniles, paz y oportunidades en el posconflicto.",
    poblacion: 22000,
    altitud: 1500,
    fundacion: 1847,
    imagen: "/images/municipios/ituango.jpg",
    escudo: "/images/escudos/ituango.png",
    alcalde: "Jhon Fredy Zapata",
    region: "Norte de Antioquia",
    cmj: {
      periodo: "2024 – 2028",
      fechaPosesion: "25 de enero de 2024",
      normaLegal: "Acuerdo Municipal N.° 002 de 2024",
      numeroCurules: 9,
      mision:
        "Ser la voz de los jóvenes de Ituango en la construcción de paz y el desarrollo sostenible del municipio, en el marco del posconflicto y la transformación social.",
      vision:
        "Para 2028, tener un consejo reconocido regionalmente por su liderazgo en procesos de paz, reconciliación y construcción de tejido social con jóvenes ituanguinos.",
      objetivos: [
          "Liderar procesos de construcción de paz y reconciliación en el municipio.",
          "Gestionar oportunidades educativas y de empleo para los jóvenes.",
          "Promover la participación política y ciudadana de la juventud ituanguina.",
          "Articular acciones con organizaciones nacionales e internacionales de paz.",
      ],
        redes: {
          facebook: "CMJ Ituango Paz y Futuro",
          instagram: "@cmjituango",
        },
    },
    integrantes: [
      {
        id: "i-itu-1",
        municipioId: "m-10",
        nombre: "Cristian David Ramírez",
        cargo: "Presidente",
        foto: "/images/integrantes/cristian-ramirez.jpg",
        email: "cdramirez.cmj@ituango.gov.co",
        telefono: "3189012345",
        edad: 27,
        periodoInicio: "2024-01-30",
        periodoFin: "2026-01-30",
        bio: "Abogado. Defensor de derechos humanos y promotor de la paz territorial en Ituango.",
      },
      {
        id: "i-itu-2",
        municipioId: "m-10",
        nombre: "Paola Andrea Suárez",
        cargo: "Vicepresidente",
        foto: "/images/integrantes/paola-suarez.jpg",
        email: "pasuarez.cmj@ituango.gov.co",
        telefono: "3101234567",
        edad: 24,
        periodoInicio: "2024-01-30",
        periodoFin: "2026-01-30",
        bio: "Trabajadora social. Lidera procesos de atención a jóvenes víctimas del conflicto.",
      },
      {
        id: "i-itu-3",
        municipioId: "m-10",
        nombre: "Luisa Fernanda Torres",
        cargo: "Secretario/a",
        foto: "/images/integrantes/luisa-torres.jpg",
        email: "lftorres.cmj@ituango.gov.co",
        telefono: "3112345678",
        edad: 20,
        periodoInicio: "2024-01-30",
        periodoFin: "2026-01-30",
        bio: "Comunicadora. Maneja los canales digitales del CMJ y documenta los procesos comunitarios.",
      },
    ],
    proyectos: [
      {
        id: "p-itu-1",
        municipioId: "m-10",
        titulo: "Centro Comunitario La Esperanza",
        descripcion:
          "Construcción y dotación de un espacio cultural y deportivo para jóvenes del municipio.",
        estado: "Completado",
        fechaInicio: "2023-08-01",
        fechaFin: "2025-01-25",
        presupuesto: 120000000,
        beneficiarios: 800,
        categoria: "Participacion",
        imagen: "/images/proyectos/centro-esperanza.jpg",
      },
      {
        id: "p-itu-2",
        municipioId: "m-10",
        titulo: "Fondo Juvenil de Emprendimiento Post-Conflicto",
        descripcion:
          "Financiación de 20 proyectos productivos de jóvenes excombatientes y víctimas del conflicto.",
        estado: "En curso",
        fechaInicio: "2025-02-01",
        presupuesto: 80000000,
        beneficiarios: 60,
        categoria: "Emprendimiento",
        imagen: "/images/proyectos/fondo-postconflicto.jpg",
      },
    ],
    noticias: [
      {
        id: "n-itu-1",
        municipioId: "m-10",
        titulo: "CMJ Ituango inaugura centro comunitario juvenil",
        resumen:
          "Tras 18 meses de gestión, el primer espacio dedicado exclusivamente a la juventud abre sus puertas.",
        contenido:
          "El Consejo Municipal de Juventud de Ituango celebró la inauguración del Centro Comunitario Juvenil 'La Esperanza', un espacio de 400 m² destinado a actividades culturales, deportivas, formativas y de emprendimiento.",
        imagen: "/images/noticias/centro-ituango.jpg",
        autor: "CMJ Ituango",
        fecha: "2025-01-28",
        categoria: "Logros",
        destacada: true,
        tags: ["infraestructura", "logro", "centro"],
      },
    ],
  },
  {
    id: "m-11",
    slug: "san-andres",
    nombre: "San Andrés",
    descripcion:
      "Municipio serrano con vocación agropecuaria. El CMJ promueve la identidad cultural andina y la participación política juvenil.",
    poblacion: 8900,
    altitud: 2700,
    fundacion: 1839,
    imagen: "/images/municipios/san-andres.jpg",
    escudo: "/images/escudos/san-andres.png",
    alcalde: "Beatriz Elena Toro",
    region: "Norte de Antioquia",
    cmj: {
      periodo: "2024 – 2028",
      fechaPosesion: "15 de febrero de 2024",
      normaLegal: "Acuerdo Municipal N.° 003 de 2024",
      numeroCurules: 7,
      mision:
        "Representar a la juventud de San Andrés de Cuerquia, promoviendo el desarrollo integral y la participación ciudadana desde una perspectiva de género y diversidad.",
      vision:
        "Ser un consejo que haya logrado incluir y representar a todos los sectores juveniles del municipio, sin discriminación, al 2028.",
      objetivos: [
          "Garantizar la participación de jóvenes de todos los sectores, incluyendo LGBTIQ+ y mujeres.",
          "Promover la equidad de género en los espacios de decisión juvenil.",
          "Fortalecer las organizaciones juveniles del municipio.",
          "Gestionar proyectos de formación en derechos humanos y ciudadanía.",
      ],
        redes: {
          instagram: "@cmj_sanandres",
        },
    },
    integrantes: [
      {
        id: "i-san-1",
        municipioId: "m-11",
        nombre: "Miguel Ángel Cardona",
        cargo: "Presidente",
        foto: "/images/integrantes/miguel-cardona.jpg",
        email: "macardona.cmj@sanandres.gov.co",
        telefono: "3123456780",
        edad: 23,
        periodoInicio: "2024-02-05",
        periodoFin: "2026-02-05",
        bio: "Docente rural. Promueve la educación política y el voto consciente entre los jóvenes.",
      },
    ],
    proyectos: [
      {
        id: "p-san-1",
        municipioId: "m-11",
        titulo: "Escuela de Democracia Juvenil",
        descripcion: "Formación política para jóvenes en edad de votar: derechos, deberes y participación electoral.",
        estado: "En curso",
        fechaInicio: "2025-01-10",
        presupuesto: 10000000,
        beneficiarios: 75,
        categoria: "Participacion",
        imagen: "/images/proyectos/escuela-democracia.jpg",
      },
    ],
    noticias: [
      {
        id: "n-san-1",
        municipioId: "m-11",
        titulo: "San Andrés registra la mayor participación juvenil electoral de la subregión",
        resumen: "Gracias al trabajo del CMJ, el 68% de los jóvenes habilitados votó en las últimas elecciones locales.",
        contenido:
          "El CMJ de San Andrés celebra que el 68% de los jóvenes entre 18 y 28 años habilitados para votar participó en las elecciones locales de 2024, siendo la cifra más alta de la subregión Norte de Antioquia. La campaña 'Tu Voto Construye' fue clave en este resultado.",
        imagen: "/images/noticias/votacion-san-andres.jpg",
        autor: "CMJ San Andrés",
        fecha: "2025-01-05",
        categoria: "Participacion",
        destacada: false,
        tags: ["electoral", "participacion", "democracia"],
      },
    ],
  },
  {
    id: "m-12",
    slug: "san-jose-de-la-montana",
    nombre: "San José de la Montaña",
    descripcion:
      "Municipio de clima frío y producción de fresas y mora. El CMJ fomenta la innovación en agricultura familiar y mercados orgánicos.",
    poblacion: 4100,
    altitud: 2800,
    fundacion: 1916,
    imagen: "/images/municipios/san-jose.jpg",
    escudo: "/images/escudos/san-jose.png",
    alcalde: "Gloria Estela Giraldo",
    region: "Norte de Antioquia",
    cmj: {
      periodo: "2024 – 2028",
      fechaPosesion: "20 de febrero de 2024",
      normaLegal: "Acuerdo Municipal N.° 002 de 2024",
      numeroCurules: 7,
      mision:
        "Fomentar el desarrollo integral de los jóvenes de San José de la Montaña, con énfasis en la producción lechera sostenible, la educación y la cultura campesina.",
      vision:
        "Ser referentes en agro-juventud, promoviendo que los jóvenes sanjosequinos vean en el campo una oportunidad de vida y progreso.",
      objetivos: [
          "Vincular a los jóvenes con proyectos de agroindustria y lechería sostenible.",
          "Promover la permanencia de los jóvenes en el campo con oportunidades reales.",
          "Fortalecer la identidad cultural campesina entre las nuevas generaciones.",
          "Articularse con el SENA y la Secretaría de Agricultura departamental.",
      ],
        redes: {
          instagram: "@cmjsanjosemontana",
        },
    },
    integrantes: [
      {
        id: "i-sjm-1",
        municipioId: "m-12",
        nombre: "Natalia Echeverri",
        cargo: "Presidente",
        foto: "/images/integrantes/natalia-echeverri.jpg",
        email: "necheverri.cmj@sanjose.gov.co",
        telefono: "3134567801",
        edad: 20,
        periodoInicio: "2024-03-10",
        periodoFin: "2026-03-10",
        bio: "Estudiante de Agronomía. Especialista en cultivo de berries y procesamiento artesanal.",
      },
    ],
    proyectos: [
      {
        id: "p-sjm-1",
        municipioId: "m-12",
        titulo: "Fresas y Moras: Tienda Online Joven",
        descripcion:
          "Plataforma de comercio electrónico para frutos rojos orgánicos cultivados por jóvenes del municipio.",
        estado: "Planificado",
        fechaInicio: "2025-06-01",
        presupuesto: 12000000,
        beneficiarios: 25,
        categoria: "Emprendimiento",
        imagen: "/images/proyectos/fresas-online.jpg",
      },
    ],
    noticias: [
      {
        id: "n-sjm-1",
        municipioId: "m-12",
        titulo: "San José de la Montaña lanza mercado orgánico juvenil",
        resumen: "El CMJ organiza un mercado mensual donde jóvenes agricultores venden directamente al consumidor.",
        contenido:
          "El primer mercado orgánico juvenil de San José de la Montaña abrió sus puertas en la plaza principal. Cada primer sábado del mes, jóvenes de la zona rural ofrecen fresas, mora, mermeladas y productos derivados sin intermediarios.",
        imagen: "/images/noticias/mercado-sanjose.jpg",
        autor: "CMJ San José de la Montaña",
        fecha: "2025-02-08",
        categoria: "Emprendimiento",
        destacada: false,
        tags: ["mercado", "organico", "fresas"],
      },
    ],
  },
  {
    id: "m-13",
    slug: "san-pedro",
    nombre: "San Pedro de los Milagros",
    descripcion:
      "Municipio lechero y quesero, con fuerte identidad ganadera. El CMJ trabaja en agroindustria juvenil y diversificación económica.",
    poblacion: 27000,
    altitud: 2475,
    fundacion: 1856,
    imagen: "/images/municipios/san-pedro.jpg",
    escudo: "/images/escudos/san-pedro.png",
    alcalde: "Jorge Hernán Galeano",
    region: "Norte de Antioquia",
    cmj: {
      periodo: "2024 – 2028",
      fechaPosesion: "1 de marzo de 2024",
      normaLegal: "Acuerdo Municipal N.° 004 de 2024",
      numeroCurules: 9,
      mision:
        "Promover el desarrollo humano y la participación ciudadana de los jóvenes de San Pedro de los Milagros, integrando cultura, deporte y emprendimiento.",
      vision:
        "En 2028, ser un consejo que haya articulado un ecosistema de oportunidades para los jóvenes sanpedrinos, con alianzas sólidas con el sector privado y la academia.",
      objetivos: [
          "Fortalecer los espacios deportivos y culturales para la juventud.",
          "Crear un fondo de emprendimiento juvenil con recursos gestionados por el consejo.",
          "Promover la educación superior y técnica para jóvenes del municipio.",
          "Articular acciones con las empresas locales del sector ganadero.",
      ],
        redes: {
          facebook: "CMJ San Pedro de los Milagros",
          instagram: "@cmj_sanpedro",
        },
    },
    integrantes: [
      {
        id: "i-spe-1",
        municipioId: "m-13",
        nombre: "Alejandro Montoya",
        cargo: "Presidente",
        foto: "/images/integrantes/alejandro-montoya.jpg",
        email: "amontoya.cmj@sanpedro.gov.co",
        telefono: "3145678902",
        edad: 25,
        periodoInicio: "2024-01-18",
        periodoFin: "2026-01-18",
        bio: "Ingeniero de Alimentos. Desarrolla nuevos productos lácteos con valor agregado.",
      },
      {
        id: "i-spe-2",
        municipioId: "m-13",
        nombre: "Camila Restrepo",
        cargo: "Secretario/a",
        foto: "/images/integrantes/camila-restrepo.jpg",
        email: "crestrepo.cmj@sanpedro.gov.co",
        telefono: "3156789013",
        edad: 21,
        periodoInicio: "2024-01-18",
        periodoFin: "2026-01-18",
        bio: "Comunicadora social. Gestiona las redes sociales y comunicaciones del CMJ.",
      },
    ],
    proyectos: [
      {
        id: "p-spe-1",
        municipioId: "m-13",
        titulo: "Queso Artesanal San Pedro: Marca Registrada",
        descripcion:
          "Registro y comercialización de queso artesanal con denominación de origen bajo gestión juvenil.",
        estado: "En curso",
        fechaInicio: "2024-10-01",
        presupuesto: 30000000,
        beneficiarios: 50,
        categoria: "Emprendimiento",
        imagen: "/images/proyectos/queso-sanpedro.jpg",
      },
    ],
    noticias: [
      {
        id: "n-spe-1",
        municipioId: "m-13",
        titulo: "CMJ San Pedro logra registro oficial del queso artesanal local",
        resumen: "El producto ya cuenta con denominación de origen y está listo para exportación.",
        contenido:
          "Tras meses de gestión, el queso artesanal de San Pedro de los Milagros obtuvo su registro ante el INVIMA y la denominación de origen, siendo el primer producto lácteo artesanal del norte antioqueño en lograrlo. El proceso fue liderado integralmente por el CMJ.",
        imagen: "/images/noticias/queso-registro.jpg",
        autor: "CMJ San Pedro",
        fecha: "2025-04-05",
        categoria: "Emprendimiento",
        destacada: true,
        tags: ["queso", "denominacion-origen", "INVIMA"],
      },
    ],
  },
  {
    id: "m-14",
    slug: "santa-rosa-de-osos",
    nombre: "Santa Rosa de Osos",
    descripcion:
      "Capital del Norte de Antioquia y ciudad universitaria. El CMJ articulado con las instituciones académicas impulsa innovación, investigación y liderazgo.",
    poblacion: 36000,
    altitud: 2550,
    fundacion: 1636,
    imagen: "/images/municipios/santa-rosa.jpg",
    escudo: "/images/escudos/santa-rosa.png",
    alcalde: "Luis Fernando Ríos",
    region: "Norte de Antioquia",
    cmj: {
      periodo: "2024 – 2028",
      fechaPosesion: "10 de enero de 2024",
      normaLegal: "Acuerdo Municipal N.° 001 de 2024",
      numeroCurules: 13,
      mision:
        "Liderar la agenda juvenil de Santa Rosa de Osos, articulando a los jóvenes con las apuestas de desarrollo del municipio capital de la subregión Norte de Antioquia.",
      vision:
        "Ser el consejo juvenil más activo y propositivo del Norte de Antioquia, referente en formulación de política pública de juventud a nivel departamental al 2028.",
      objetivos: [
          "Articular la agenda juvenil con el Plan de Desarrollo Municipal.",
          "Promover el acceso a educación de calidad para todos los jóvenes del municipio.",
          "Fortalecer la participación política y electoral de la juventud santarrosana.",
          "Gestionar proyectos de impacto regional en alianza con los demás CMJ del Norte.",
      ],
        redes: {
          facebook: "CMJ Santa Rosa de Osos",
          instagram: "@cmj_santarosa",
          tiktok: "@cmjsantarosa",
        },
    },
    integrantes: [
      {
        id: "i-sar-1",
        municipioId: "m-14",
        nombre: "Manuela Arango",
        cargo: "Presidente",
        foto: "/images/integrantes/manuela-arango.jpg",
        email: "marango.cmj@santarosa.gov.co",
        telefono: "3167890124",
        edad: 26,
        periodoInicio: "2024-01-12",
        periodoFin: "2026-01-12",
        bio: "Politóloga. Lidera el CMJ más grande del norte de Antioquia con enfoque en gobernanza juvenil.",
      },
      {
        id: "i-sar-2",
        municipioId: "m-14",
        nombre: "Juan Pablo Escobar",
        cargo: "Vicepresidente",
        foto: "/images/integrantes/juan-escobar.jpg",
        email: "jpescobar.cmj@santarosa.gov.co",
        telefono: "3178901235",
        edad: 24,
        periodoInicio: "2024-01-12",
        periodoFin: "2026-01-12",
        bio: "Economista. Experto en políticas públicas para la juventud y presupuesto participativo.",
      },
      {
        id: "i-sar-3",
        municipioId: "m-14",
        nombre: "Daniela Osorio",
        cargo: "Tesorero/a",
        foto: "/images/integrantes/daniela-osorio.jpg",
        email: "dosorio.cmj@santarosa.gov.co",
        telefono: "3189012346",
        edad: 22,
        periodoInicio: "2024-01-12",
        periodoFin: "2026-01-12",
        bio: "Administradora de empresas. Garantiza la transparencia financiera del CMJ.",
      },
      {
        id: "i-sar-4",
        municipioId: "m-14",
        nombre: "Ricardo Saldarriaga",
        cargo: "Vocal",
        foto: "/images/integrantes/ricardo-saldarriaga.jpg",
        email: "rsaldarriaga.cmj@santarosa.gov.co",
        telefono: "3100123456",
        edad: 20,
        periodoInicio: "2024-01-12",
        periodoFin: "2026-01-12",
        bio: "Estudiante de Ingeniería de Sistemas. Responsable de la plataforma digital del CMJ.",
      },
    ],
    proyectos: [
      {
        id: "p-sar-1",
        municipioId: "m-14",
        titulo: "Hub de Innovación Juvenil Norte",
        descripcion:
          "Espacio de coworking y laboratorio de ideas para jóvenes emprendedores e investigadores de la subregión.",
        estado: "En curso",
        fechaInicio: "2024-09-15",
        presupuesto: 150000000,
        beneficiarios: 300,
        categoria: "Emprendimiento",
        imagen: "/images/proyectos/hub-innovacion.jpg",
      },
      {
        id: "p-sar-2",
        municipioId: "m-14",
        titulo: "Semillero de Investigación Juvenil",
        descripcion:
          "Programa de investigación aplicada liderado por jóvenes universitarios para resolver problemas del territorio.",
        estado: "En curso",
        fechaInicio: "2025-02-15",
        presupuesto: 45000000,
        beneficiarios: 80,
        categoria: "Educacion",
        imagen: "/images/proyectos/semillero.jpg",
      },
    ],
    noticias: [
      {
        id: "n-sar-1",
        municipioId: "m-14",
        titulo: "Santa Rosa de Osos abre el Hub de Innovación Juvenil Norte",
        resumen:
          "El espacio de coworking para jóvenes emprendedores ya tiene más de 150 miembros activos.",
        contenido:
          "El Hub de Innovación Juvenil Norte, ubicado en el centro de Santa Rosa de Osos, abrió oficialmente con 150 miembros activos y 18 proyectos en marcha. El espacio cuenta con laboratorio maker, sala de podcast, zona de trabajo colaborativo y mentoría empresarial.",
        imagen: "/images/noticias/hub-santarosa.jpg",
        autor: "CMJ Santa Rosa de Osos",
        fecha: "2025-03-20",
        categoria: "Emprendimiento",
        destacada: true,
        tags: ["hub", "innovacion", "emprendimiento"],
      },
    ],
  },
  {
    id: "m-15",
    slug: "toledo",
    nombre: "Toledo",
    descripcion:
      "Municipio fronterizo con vocación turística y minera. El CMJ trabaja en turismo de aventura y gestión ambiental del río San Juan.",
    poblacion: 9200,
    altitud: 1350,
    fundacion: 1912,
    imagen: "/images/municipios/toledo.jpg",
    escudo: "/images/escudos/toledo.png",
    alcalde: "Rosa Inés Martínez",
    region: "Norte de Antioquia",
    cmj: {
      periodo: "2024 – 2028",
      fechaPosesion: "5 de marzo de 2024",
      normaLegal: "Acuerdo Municipal N.° 003 de 2024",
      numeroCurules: 7,
      mision:
        "Representar a la juventud de Toledo, impulsando el desarrollo rural, la identidad territorial y la participación activa de los jóvenes en la construcción del municipio.",
      vision:
        "Ser un consejo que haya logrado que los jóvenes de Toledo vean en su territorio una tierra de oportunidades, con proyectos sostenibles y de largo plazo.",
      objetivos: [
          "Fomentar el arraigo territorial y el amor por el campo entre los jóvenes.",
          "Gestionar proyectos productivos agropecuarios con enfoque juvenil.",
          "Promover la formación técnica y el emprendimiento rural.",
          "Articularse con la Gobernación de Antioquia para acceso a programas departamentales.",
      ],
        redes: {
          instagram: "@cmj_toledo_ant",
        },
    },
    integrantes: [
      {
        id: "i-tol-1",
        municipioId: "m-15",
        nombre: "Kevin Andrés Gil",
        cargo: "Presidente",
        foto: "/images/integrantes/kevin-gil.jpg",
        email: "kagil.cmj@toledo.gov.co",
        telefono: "3111234567",
        edad: 23,
        periodoInicio: "2024-02-20",
        periodoFin: "2026-02-20",
        bio: "Guía de turismo de aventura. Especialista en deportes de río y canopy.",
      },
    ],
    proyectos: [
      {
        id: "p-tol-1",
        municipioId: "m-15",
        titulo: "Turismo de Aventura Río San Juan",
        descripcion:
          "Desarrollo de paquetes turísticos de rafting, kayak y senderismo liderados por jóvenes guías.",
        estado: "En curso",
        fechaInicio: "2025-01-05",
        presupuesto: 18000000,
        beneficiarios: 40,
        categoria: "Emprendimiento",
        imagen: "/images/proyectos/turismo-aventura.jpg",
      },
    ],
    noticias: [
      {
        id: "n-tol-1",
        municipioId: "m-15",
        titulo: "Toledo se posiciona como destino de turismo de aventura del norte",
        resumen: "Los paquetes turísticos del CMJ han atraído más de 500 visitantes en el primer trimestre.",
        contenido:
          "El proyecto de Turismo de Aventura Río San Juan del CMJ de Toledo ha logrado atraer 512 turistas en su primer trimestre de operación. Los paquetes de rafting y senderismo han generado ingresos por más de $35 millones para los jóvenes guías certificados.",
        imagen: "/images/noticias/turismo-toledo.jpg",
        autor: "CMJ Toledo",
        fecha: "2025-04-10",
        categoria: "Turismo",
        destacada: false,
        tags: ["turismo", "aventura", "rio"],
      },
    ],
  },
  {
    id: "m-16",
    slug: "valdivia",
    nombre: "Valdivia",
    descripcion:
      "Municipio bañado por el río Cauca. El CMJ trabaja en recuperación ambiental del río y medios de vida alternativos para jóvenes.",
    poblacion: 18500,
    altitud: 800,
    fundacion: 1878,
    imagen: "/images/municipios/valdivia.jpg",
    escudo: "/images/escudos/valdivia.png",
    alcalde: "Pedro Pablo Agudelo",
    region: "Norte de Antioquia",
    cmj: {
      periodo: "2024 – 2028",
      fechaPosesion: "12 de marzo de 2024",
      normaLegal: "Acuerdo Municipal N.° 002 de 2024",
      numeroCurules: 9,
      mision:
        "Promover la participación y el desarrollo de los jóvenes de Valdivia, en el marco de la construcción de paz y el aprovechamiento sostenible de los recursos naturales del municipio.",
      vision:
        "Para 2028, ser un consejo que haya contribuido significativamente a la paz territorial y al desarrollo humano de la juventud valdiviense.",
      objetivos: [
          "Liderar acciones de construcción de paz y convivencia en el municipio.",
          "Gestionar proyectos de aprovechamiento sostenible de los recursos naturales.",
          "Promover el acceso a educación y oportunidades de empleo para los jóvenes.",
          "Fortalecer los vínculos entre los jóvenes urbanos y rurales del municipio.",
      ],
        redes: {
          instagram: "@cmjvaldivia",
        },
    },
    integrantes: [
      {
        id: "i-val-1",
        municipioId: "m-16",
        nombre: "Lina María Castaño",
        cargo: "Presidente",
        foto: "/images/integrantes/lina-castano.jpg",
        email: "lmcastano.cmj@valdivia.gov.co",
        telefono: "3122345678",
        edad: 24,
        periodoInicio: "2024-02-28",
        periodoFin: "2026-02-28",
        bio: "Bióloga marina. Trabaja en restauración de ecosistemas fluviales y educación ambiental.",
      },
    ],
    proyectos: [
      {
        id: "p-val-1",
        municipioId: "m-16",
        titulo: "Guardianes del Río Cauca",
        descripcion:
          "Monitoreo comunitario de la calidad del agua y reforestación de riberas por jóvenes voluntarios.",
        estado: "En curso",
        fechaInicio: "2024-08-01",
        presupuesto: 24000000,
        beneficiarios: 80,
        categoria: "Medio Ambiente",
        imagen: "/images/proyectos/guardianes-cauca.jpg",
      },
    ],
    noticias: [
      {
        id: "n-val-1",
        municipioId: "m-16",
        titulo: "CMJ Valdivia planta 5.000 árboles en riberas del Cauca",
        resumen: "La jornada de reforestación masiva del proyecto Guardianes del Río contó con 200 jóvenes voluntarios.",
        contenido:
          "En una jornada de dos días, más de 200 jóvenes del CMJ de Valdivia y colegios del municipio plantaron 5.000 árboles nativos en las riberas del río Cauca. La acción hace parte del proyecto Guardianes del Río Cauca y busca recuperar el ecosistema ribereño.",
        imagen: "/images/noticias/reforestacion-valdivia.jpg",
        autor: "CMJ Valdivia",
        fecha: "2025-03-22",
        categoria: "Medio Ambiente",
        destacada: false,
        tags: ["reforestacion", "cauca", "ambiente"],
      },
    ],
  },
  {
    id: "m-17",
    slug: "yarumal",
    nombre: "Yarumal",
    descripcion:
      "Municipio más grande del Norte de Antioquia y sede de la Mesa Regional CMJ. Centro educativo y comercial de la subregión.",
    poblacion: 44000,
    altitud: 2200,
    fundacion: 1787,
    imagen: "/images/municipios/yarumal.jpg",
    escudo: "/images/escudos/yarumal.png",
    alcalde: "Néstor Emilio García",
    region: "Norte de Antioquia",
    cmj: {
      periodo: "2024 – 2028",
      fechaPosesion: "15 de enero de 2024",
      normaLegal: "Acuerdo Municipal N.° 001 de 2024",
      numeroCurules: 13,
      mision:
        "Ser el epicentro de la articulación juvenil del Norte de Antioquia, liderando procesos de participación, formación y desarrollo que posicionen a Yarumal como capital juvenil de la subregión.",
      vision:
        "En 2028, consolidar a Yarumal como la ciudad de los jóvenes líderes del Norte de Antioquia, con una política pública robusta y un tejido organizativo juvenil sólido.",
      objetivos: [
          "Articular la agenda juvenil regional desde Yarumal como municipio cabecera.",
          "Promover el acceso a educación superior y técnica de calidad.",
          "Fortalecer el ecosistema emprendedor juvenil con acceso a crédito y mentoría.",
          "Consolidar el Encuentro Regional CMJ como evento anual de referencia.",
      ],
        redes: {
          facebook: "CMJ Yarumal Oficial",
          instagram: "@cmjarumal",
          tiktok: "@cmjyarumal",
        },
    },
    integrantes: [
      {
        id: "i-yar-1",
        municipioId: "m-17",
        nombre: "Sofía Isabel Gómez",
        cargo: "Presidente",
        foto: "/images/integrantes/sofia-gomez.jpg",
        email: "sigomez.cmj@yarumal.gov.co",
        telefono: "3133456789",
        edad: 27,
        periodoInicio: "2024-01-08",
        periodoFin: "2026-01-08",
        bio: "Abogada y politóloga. Coordinadora de la Mesa Regional de CMJ del Norte de Antioquia.",
      },
      {
        id: "i-yar-2",
        municipioId: "m-17",
        nombre: "Samuel Hernández",
        cargo: "Vicepresidente",
        foto: "/images/integrantes/samuel-hernandez.jpg",
        email: "shernandez.cmj@yarumal.gov.co",
        telefono: "3144567890",
        edad: 24,
        periodoInicio: "2024-01-08",
        periodoFin: "2026-01-08",
        bio: "Comunicador. Lidera la estrategia digital de los CMJ del norte y el boletín regional.",
      },
      {
        id: "i-yar-3",
        municipioId: "m-17",
        nombre: "Valeria Jaramillo",
        cargo: "Secretario/a",
        foto: "/images/integrantes/valeria-jaramillo.jpg",
        email: "vjaramillo.cmj@yarumal.gov.co",
        telefono: "3155678901",
        edad: 21,
        periodoInicio: "2024-01-08",
        periodoFin: "2026-01-08",
        bio: "Administradora pública. Encargada de la articulación con la alcaldía y gobernación.",
      },
      {
        id: "i-yar-4",
        municipioId: "m-17",
        nombre: "Tomás Aguilar",
        cargo: "Tesorero/a",
        foto: "/images/integrantes/tomas-aguilar.jpg",
        email: "taguilar.cmj@yarumal.gov.co",
        telefono: "3166789012",
        edad: 22,
        periodoInicio: "2024-01-08",
        periodoFin: "2026-01-08",
        bio: "Contador público. Gestiona los recursos del CMJ con total transparencia.",
      },
    ],
    proyectos: [
      {
        id: "p-yar-1",
        municipioId: "m-17",
        titulo: "Plataforma Digital Jóvenes Norte",
        descripcion:
          "Portal web y app para conectar a los jóvenes de la subregión con oportunidades, convocatorias y servicios.",
        estado: "En curso",
        fechaInicio: "2025-01-01",
        presupuesto: 60000000,
        beneficiarios: 5000,
        categoria: "Participacion",
        imagen: "/images/proyectos/plataforma-digital.jpg",
      },
      {
        id: "p-yar-2",
        municipioId: "m-17",
        titulo: "Encuentro Regional de Juventudes 2025",
        descripcion:
          "Organización del evento anual que reúne a los CMJ de los 17 municipios del Norte de Antioquia.",
        estado: "En curso",
        fechaInicio: "2025-03-01",
        fechaFin: "2025-03-16",
        presupuesto: 40000000,
        beneficiarios: 300,
        categoria: "Participacion",
        imagen: "/images/proyectos/encuentro-regional.jpg",
      },
    ],
    noticias: [
      {
        id: "n-yar-1",
        municipioId: "m-17",
        titulo: "Yarumal sede del Encuentro Regional de Juventudes 2025",
        resumen: "Más de 200 jóvenes de los 17 municipios del norte se congregaron para trazar la hoja de ruta 2025-2026.",
        contenido:
          "El Primer Encuentro Regional de Juventudes 2025 se realizó en Yarumal con la participación de delegados de todos los Consejos Municipales de Juventud del Norte de Antioquia. Se aprobó la Agenda Juvenil Regional y se eligió la Mesa Coordinadora.",
        imagen: "/images/noticias/encuentro-yarumal.jpg",
        autor: "CMJ Yarumal",
        fecha: "2025-03-17",
        categoria: "Eventos",
        destacada: true,
        tags: ["encuentro", "regional", "yarumal"],
      },
    ],
  },
]

// ─── PQR mock data ─────────────────────────────────────────────────────────
export const pqrsMock: PQR[] = [
  {
    id: "pqr-001",
    tipo: "Peticion",
    municipioId: "m-17",
    nombre: "Martín Arbeláez",
    email: "martin.arbe@gmail.com",
    telefono: "3101112233",
    cedula: "1001234567",
    asunto: "Solicitud de información sobre convocatorias",
    descripcion:
      "Me gustaría obtener información detallada sobre las convocatorias del Fondo de Iniciativas Juveniles 2025, los requisitos de inscripción y los plazos disponibles.",
    estado: "Respondida",
    fechaCreacion: "2025-03-20",
    fechaRespuesta: "2025-03-25",
    respuesta:
      "Estimado Martín, puede consultar la convocatoria completa en el portal de la Gobernación de Antioquia. Los requisitos son: ser mayor de 14 y menor de 28 años, residir en el municipio y presentar proyecto formulado con presupuesto. Plazo: 30 de abril de 2025.",
  },
  {
    id: "pqr-002",
    tipo: "Queja",
    municipioId: "m-14",
    nombre: "Andrea Quintero",
    email: "andrea.q@hotmail.com",
    telefono: "3122223344",
    cedula: "1002345678",
    asunto: "Falta de información sobre actividades del CMJ",
    descripcion:
      "El CMJ de Santa Rosa no ha publicado ninguna actividad en los últimos 2 meses. No hay información actualizada en ningún canal oficial.",
    estado: "En revision",
    fechaCreacion: "2025-04-01",
  },
  {
    id: "pqr-003",
    tipo: "Sugerencia",
    municipioId: "m-10",
    nombre: "Carlos Bedoya",
    email: "cbedoya@gmail.com",
    telefono: "3133334455",
    cedula: "1003456789",
    asunto: "Crear un grupo de WhatsApp regional de CMJ",
    descripcion:
      "Sería muy útil contar con un canal de comunicación directo entre los CMJ de todos los municipios para compartir iniciativas rápidamente.",
    estado: "Pendiente",
    fechaCreacion: "2025-04-12",
  },
  {
    id: "pqr-004",
    tipo: "Reclamo",
    municipioId: "m-01",
    nombre: "Patricia Salinas",
    email: "patricia.s@gmail.com",
    telefono: "3144445566",
    cedula: "1004567890",
    asunto: "Proyecto aprobado sin ejecución",
    descripcion:
      "Nuestro proyecto de emprendimiento fue aprobado en octubre de 2024 pero a la fecha no se han desembolsado los recursos prometidos. Llevamos 6 meses esperando.",
    estado: "En revision",
    fechaCreacion: "2025-04-05",
  },
]

// ─── Utility helpers ───────────────────────────────────────────────────────
export function getMunicipioBySlug(slug: string): Municipio | undefined {
  return municipios.find((m) => m.slug === slug)
}

export function getAllNoticias(): Noticia[] {
  const all: Noticia[] = [...noticiasRegionales]
  municipios.forEach((m) => all.push(...m.noticias))
  return all.sort((a, b) => new Date(b.fecha).getTime() - new Date(a.fecha).getTime())
}

export function getNoticiaById(id: string): Noticia | undefined {
  return getAllNoticias().find((n) => n.id === id)
}

export const stats = {
  municipios: 17,
  jovenes: 320,
  proyectos: municipios.reduce((acc, m) => acc + m.proyectos.length, 0),
  noticias: getAllNoticias().length,
}
